files/service/maldet.service
files/service/maldet.sh
files/uninstall.sh
install.sh

The install and uninstall scripts now properly detect if you are running systemd or sysvinit.
Note: The startup scripts expect that you have paths defined in /usr/local/maldetect/monitor_paths

This adds system startup scripts for maldet monitoring.

---

files/uninstall.sh
install.sh

Makes sure that maldet startup scripts are not installed for FreeBSD as it doesn't support inotify file monitoring. Also fixed the uninstaller to turn off monitoring before maldet is removed.

Makes sure that maldet startup scripts are not installed for FreeBSD

---

files/hookscan.sh

Maybe it's better to use 'which' to find the path of the binary. But I think this is not needed in this case.

Removing absolut path of 'pidof'

---

files/conf.maldet
files/internals/functions
files/internals/internals.conf
files/internals/scan.etpl

The shebang in this files is not needed, as those files are included into
other files. In this case the shebang is not needed.
I droped the shebang in my Debian package via https://github.com/waja/maldetect/blob/master/debian/patches/0006-20_maldetect-remove-shebang.patch. Lintian is complaining about the unneeded shebang.

Droping unneeded shebang

---

files/service/maldet.sh

The stop function will now log the right success and failure message under Debian.

Debianise stop function

---

files/internals/functions

More info in rfxn/linux-malware-detect#106. This should prevent maldet consuming all the memory available in the system.
Variable `inotify_cycle_runtime` is initialized out of the new loop.

Solve nested call monitor_cycle memory problem

---

files/internals/functions

Use PGID to kill all zombie child processe instead of just PID

Fix zombie child rfxn/linux-malware-detect#101

---

files/internals/functions

inotifywait doesn't support -d and -o options in Centos 6 and Ubuntu 12. This solution provided by @maxxer solves the issue and should work for everyone.

Fix issue rfxn/linux-malware-detect#84

---

files/service/maldet.sh

Debian has it's own version of sysconfig stored in /etc/default/.

Accomodate Debians version of sysconfig

---

cron.daily

The cron should read settings from sysconfig, otherwise it will missing settings set there such as turning off auto update.

Pull in settings from sysconfig

---

cron.daily
files/hookscan.sh
files/internals/functions
files/internals/internals.conf
files/maldet
files/service/maldet.sh

There are several definitions of locations all over the files. This is
a try to reduce them and source them from the internals.conf. Some of
them are even hardcoded.
This effort tries to reduce the work when customized (eg. FHS compatible)
are used, for example downstream packaging.
A small amount of the hardcoded stuff is still untouched (installsh, maldet.sysconf and maldet.service) for obvious reasons.
Reducing the (hardcoded) locations is a first step to fix #137.

Trying to reduce redundant paths definitions

---

cron.daily
files/hookscan.sh
files/maldet
files/service/maldet.sh

Since $inspath is defined in internals.conf and we source this, we don't
need to define it explicitly in this files.

Remove unneeded inspath variable definition.

---

.ca.def
files/internals/functions

The shebang is not needed for sourced files. At least [lintian](https://lintian.debian.org/) is [complaining](https://lintian.debian.org/tags/script-not-executable.html).

Removing shebang from source files

---

files/internals/internals.conf

Libraries for the binaries in /\*/bin/ and /\*/sbin/ should go into /\*/lib.
See https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard for example.
This is related to #137

Own variable libpath to separate libraries.

---

files/maldet

- New versions of 'chown' don't use . (dot) to separate user and group
- In 'chown', group names are not always the same as user names. So "chown -R $user.$user" is not good in those circumstances and breaks permissions of those directories while public_scan is enabled. Moreover, not good to hide stderr while $user:$user is not working.
- There's no need to hide stderr, as these messages are extremely helpful for debugging purposes, and for watching that everything is fine to end-users, with different platforms.

fix code in maldet for --mkpubpaths option to be cross-platform

---

install.sh

Hi,
this is the most minimal change possible for #66 in the installer.
It will use uname -s which means:
>   -s      Write the name of the operating system implementation to standard output"
I'll try to revisit freebsd support when i might be able to do more. (think: early '17)

a working freebsd detection

---

files/internals/functions
files/internals/internals.conf

Makes it easier to change (and replace) wget options at a unique place.

wgetopt variable for general used wget options

---

cron.daily
files/internals/functions
files/service/maldet.sh

From the grep manpage:
-E, --extended-regexp
Interpret PATTERN as an extended regular  expression  (ERE,  see
below).  (-E is specified by POSIX.)
Direct invocation as either egrep or fgrep is deprecated, but is provided to
allow historical applications that rely on them to run unmodified.

Replace egrep with posix 'grep -e'

---

files/conf.maldet
files/service/maldet.service

The current maldet.service script always starts maldet in monitor mode using
the monitor_paths file. Let's set the monitor mode based on the value for
$default_monitor_mode sourced from conf.maldet.
I don't know if there's a way to do the same IF structure found in maldet.sh in
a systemd unit. We're stuck with relying solely on conf.maldet, since
/etc/sysconfig/maldet is setting a value for a different variable,
$MONITOR_MODE.
Resource:
https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

Systemd maldet.service should source a value for default_monitor_mode.

---

files/internals/functions

inotifywait is using POSIX extended regular expression for exclude.
From man page:
```
--exclude <pattern>
Do not process any events whose filename matches the specified POSIX extended regular expression, case sensitive.
```
Fix #205

Fix inotifywait exclude.

---

files/internals/functions

In an edge case where md5v2.dat is an empty file, not having this variable set
causes clamscan to fail to run

clamscan_max_filesize not set

---

cron.daily
files/conf.maldet

[Issue 260](https://github.com/rfxn/linux-malware-detect/issues/260) requests the ability to disable daily scans by setting a config option within the conf.maldet file. It seemed really easy to implement, and I had a few spare minutes, so I didn't see any reason not to.
I do not BELIEVE that any changes are necessary to install.sh or compat.conf (or various other files called or referenced during the update process) in order to get this in place, but if there's something I've overlooked, point me in the right direction, and I'll be glad to make the necessary changes and resubmit.

Ability to disable cron scan via conf

---

files/internals/functions

When scanning, the "find" command only seems to be used if the script is NOT given a file list, so there's no reason to error out if "find" isn't present if there IS a file list.

Don't need "find" if given a file list

---

files/maldet

**Problem:** When maldet parses the "--config-option" argument, it does so with the following string of commands:
```
echo $1 | sed -e 's/--config-option //' -e 's/-co //' | tr -d ' ' | tr ',' '\n' > $tmpco
```
Because of this, config options that include spaces lose those spaces, and config options that include commas get broken up. Thus the following two legitimate config options do not work as intended:
```
scan_tmpdir_paths="/tmp /var/tmp /dev/shm"
inotify_docroot="public_html,public_ftp"
```
Instead they are transformed into the following:
```
scan_tmpdir_paths=/tmp/var/tmp/dev/shm
inotify_docroot=public_html
public_ftp
```
Getting around these oddities without changing the currently defined formatting for this command-line option is probably more complicated than it needs to be. The …

Fixed "-co" to work with spaces and commas

---

files/maldet

Maldet begins launching jobs before it finishes parsing the command line arguments.
This results in two potential issues: First, it's possible for Maldet to begin a process without having applied all of the options that the user intended. For example, this the command
```
maldet -a /home/user/public_html/ -b
```
does not start the job in the background as was intended, but instead in the foreground.
Another good example where it's common to want this functionality is with the "--help" flag: if a user is trying to put together the arguments that they want, but stumbles on syntax part way through, it's useful if they can just append "--help" to what they have so far, and get the output that they're looking for. Once they've read it, they can press the up arrow, hit backspace a few times, …

Parse all arguments before launching jobs

---

files/maldet

Three key changes here:
1. `'s/\(, *[a-z_]*=\)/\n\1\n/g'` is changed to `'s/\(, *[a-zA-Z0-9_][a-zA-Z0-9_]*=\)/\n\1\n/g'`. This accounts for all variable names with capital letters and numbers. **conf.maldet** doesn't have them, but **internals.conf** and **/etc/sysconfig/maldet** have a few, and while the help text indicates that "-co" is just for **conf.maldet**, technically there has never been anything stopping it from being used for those other configurations previously. It also requires there to be at least one character before the equals sign in order to match the regex, (having zero characters shouldn't be a thing that would ever happen if the argument is used correctly, but better to be safe than sorry)
2. After writing to and reading from the file that this creates, `source …

Further changes to "-co"

---

README
files/internals/functions
files/maldet
files/maldet.1

This dumps the report to stdout instead of trying to open an editor. This makes it possible to extract reports in unattended contexts/scripting.
This addresses https://github.com/rfxn/linux-malware-detect/issues/290#issuecomment-622377633

[Change] add new flag: -D|--dump-report

---

README

Just noticed my mistake in https://github.com/rfxn/linux-malware-detect/pull/362/files#diff-9acbdde66a0629e3aef2b91ad13bcca8R260

fix README reference to -E --dump-report

---

files/internals/functions

The log for quarantine has quotes around the file path which helps with log file parsing, however the restore log does not have quotes which makes it difficult to parse the file names from the log. Adding quotes would make it match the logging for quarantines and easier to parse the file paths.

Add quotes around restore file paths.

---

files/internals/functions
files/internals/internals.conf

We are looking to use logrotate to manage the life cycle of the maldet log rather than having maldet auto truncate the log when its larger than 20,000 lines long. This commit adds the option to enable the truncating with the default set to enabled which will allow override via the conf.maldet file.

Add option to allow disabling log truncating of maldet log.

---

files/conf.maldet
files/internals/functions

Because I run Linux Malware Detect (LMD) on several machines and clamd uses a lot of memory these days, I wanted to use remote clamd. Initially, I just used `clamdscan_extraopts=/etc/clamd.d/clamd.remote.conf` in my configuration, but for some reason that only worked for a couple of minutes - at some point, LMD started calling clamdscan without that option...
To address this, I:
1. made up 3 new configuration options in config file:
- `remote_clamd="/etc/clamd.d/clamd.remote.conf"` - this is name of the file that clamdscan uses and should contain the address and port of remote clamd:
```
TCPSocket3310
TCPAddr clamd.example.com
```
`$remote_clamd` is later used as the config file for clamdscan (`clamdscan -c $remote_clamd`).
Because temporary errors are more likely with a remote clamd, I …

Remote clamd

---

files/conf.maldet
files/internals/functions
files/internals/importconf
files/internals/internals.conf
files/internals/panel_alert.etpl

Adds functionality to enable alerts to control panel user contact emails. Includes the following functions:
- Auto detects control panel, if one is installed (currently supports cPanel and Interworx)
- Obtains contact emails through panel-native tools for a given account
- Sends alerts with a file hit list to discovered contact emails
- Add detect_control_panel function to files/internals/functions to determine installed control panel.
- Add get_panel_contacts to files/internals/functions to discover contact emails
- Add configuration options for From, Subject, Reply-To headers on alert emails
- Add flag to enable these alerts (requires email_alert to be enabled as well)
- Add internal configuration to set the user alert template location
- Add a base template that will be used to create …

Control panel user alerts

---

files/conf.maldet
files/internals/functions

Hello,
I'm using both slack and telegram to receive reports
I think there are many people have the same demand
I created this pull request to do it

sent report to a telegram channel
